### ISSUE TITLE
I can't init the project! Who can help me

### ISSUE THREAD

**Issue by hanhan9449** [alibaba/pipcook#112]
I use archlinux, nvm, node 13.13.0, python 3.8.3
```bash
~/CODE/pipcook-example » pipcook init                            han@archlinux
? which client do you want to use? npm
⠋ installing pipcook[..................] / rollbackFailedOptional: verb npm-sess
> @pipcook/boa@0.5.2 install /home/han/CODE/pipcook-example/node_modules/@pipcook/boa
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: getaddrinfo EAI_AGAIN nodejs.org
gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
gyp ERR! System Linux 5.6.5-arch3-1
gyp ERR! command "/home/han/.nvm/versions/node/v13.13.0/bin/node" "/home/han/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/han/CODE/pipcook-example/node_modules/@pipcook/boa
gyp ERR! node -v v13.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN pipcook-example@1.0.0 No description
npm WARN pipcook-example@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pipcook/boa@0.5.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pipcook/boa@0.5.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/han/.npm/_logs/2020-04-21T02_58_25_001Z-debug.log
✖ install Error: Command failed: npm install @pipcook/boa --save error

```

**Comment by Txiaozhe** [comment]
Could you please retry it use a lower version node? Such v10 or v12 LTS version.

**Comment by yorkie** [comment]
It seems that you got a networking error when gyp downloading Node.js headers:

```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: getaddrinfo EAI_AGAIN nodejs.org
gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
gyp ERR! System Linux 5.6.5-arch3-1
```

Could you please try again later?

**Comment by yorkie** [comment]
@hanhan9449 Do you use mac and homebrew installed?

**Comment by hanhan9449** [comment]
I use nvm on archlinux



---Original---

**Comment by yorkie** [comment]
Our latest released version don't support Linux because of Boa, but our master has supported that, may I ask you to follow the instructions: https://github.com/alibaba/pipcook#developers, thank you @hanhan9449.

**Comment by utkobe** [comment]
@hanhan9449 We have released the version in which boa will support linux. Please try to update the @pipcook/pipcook-cli to latest version and try pipcook init again :)

**Comment by yorkie** [comment]
Closing this because of inactivity, feel free to reopen it if something still not working.
