### ISSUE TITLE
cli: build test case for workflow of cli

### ISSUE THREAD

**Issue by Txiaozhe** [alibaba/pipcook#161]
- test basic info for cli
  - [x] -v, --version
  - [x] -h, --help for all
- test basic usage for cli init
  - [x] pipcook init --beta
  - [x] pipcook init --tuna
  - [ ] check the init result
- test basic usage for cli dev-plugin
  - [x] pipcook dev-plugin
- test basic usage for cli run
  - [x] pipcook run: run bayes-text-classification
- test basic usage for cli serve
  - [ ] pipcook serve

And what other should be test, please give your advices:)

**Comment by yorkie** [comment]
It seems the CLI workflow doesn't work yet, see: https://github.com/alibaba/pipcook/runs/640227308.

**Comment by yorkie** [comment]
In detailed, I found the following errors:

```
> @pipcook/boa@0.5.0-beta install /home/runner/work/pipcook/pipcook/myworkspace/init2/node_modules/@pipcook/boa
> node-gyp rebuild

make: Entering directory '/home/runner/work/pipcook/pipcook/myworkspace/init2/node_modules/@pipcook/boa/build'
  CXX(target) Release/obj.target/boa/src/binding.o
In file included from ../src/core/module.h:3:0,
                 from ../src/binding.cc:1:
../src/core/common.h:4:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
boa.target.mk:119: recipe for target 'Release/obj.target/boa/src/binding.o' failed
```

This might be caused by installing beta which is not latest boa, my suggestion is to remove the --beta test, which is useless.

**Comment by yorkie** [comment]
And the plugin-dev test case failed by the following:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([Function])
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
    at /home/runner/work/pipcook/pipcook/packages/cli/dist/commands/devPlugin.js:38:34
    at Generator.next (<anonymous>)
    at /home/runner/work/pipcook/pipcook/packages/cli/dist/commands/devPlugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/pipcook/pipcook/packages/cli/dist/commands/devPlugin.js:4:12)
    at Command.exports.devPlugin (/home/runner/work/pipcook/pipcook/packages/cli/dist/commands/devPlugin.js:24:41)
    at Command.listener (/home/runner/work/pipcook/pipcook/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:310:20) {
  code: 'ERR_INVALID_ARG_TYPE'
}
(node:8071) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: rimraf: missing path
    at Object.rimrafSync [as removeSync] (/home/runner/work/pipcook/pipcook/node_modules/fs-extra/lib/remove/rimraf.js:231:3)
    at /home/runner/work/pipcook/pipcook/packages/cli/dist/commands/devPlugin.js:51:28
    at Generator.next (<anonymous>)
    at /home/runner/work/pipcook/pipcook/packages/cli/dist/commands/devPlugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/pipcook/pipcook/packages/cli/dist/commands/devPlugin.js:4:12)
    at Command.exports.devPlugin (/home/runner/work/pipcook/pipcook/packages/cli/dist/commands/devPlugin.js:24:41)
    at Command.listener (/home/runner/work/pipcook/pipcook/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:310:20)
    at Command.parseArgs (/home/runner/work/pipcook/pipcook/node_modules/commander/index.js:892:12)
```

**Comment by yorkie** [comment]
And the run pipeline is also failed, see below error:

```
../test/text-bayes-classification.json not exists
```

**Comment by yorkie** [comment]
And we need to see why the CI is green by the above errors :(

**Comment by Txiaozhe** [comment]
> And we need to see why the CI is green by the above errors :(

I will see:(

**Comment by Txiaozhe** [comment]
test case for cli merged in #162, so close this issue:)

**Comment by Txiaozhe** [comment]
reopen because test case is not complete:(
