### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by FeelyChau** [alibaba/pipcook#267]
run
```sh
$ npm run build
```
got this error:
```sh
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'compile' ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle @pipcook/plugins-textline-data-access@0.6.0~precompile: @pipcook/plugins-textline-data-access@0.6.0
6 info lifecycle @pipcook/plugins-textline-data-access@0.6.0~compile: @pipcook/plugins-textline-data-access@0.6.0
7 verbose lifecycle @pipcook/plugins-textline-data-access@0.6.0~compile: unsafe-perm in lifecycle true
8 verbose lifecycle @pipcook/plugins-textline-data-access@0.6.0~compile: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/tmp/pipcook/packages/plugins/data-access/textline-data-access/node_modules/.bin:/root/tmp/pipcook/packages/plugins/data-access/textline-data-access/node_modules/.bin:/root/tmp/pipcook/packages/plugins/data-access/node_modules/.bin:/root/tmp/pipcook/packages/plugins/node_modules/.bin:/root/tmp/pipcook/packages/node_modules/.bin:/root/tmp/pipcook/node_modules/.bin:/root/tmp/node_modules/.bin:/root/node_modules/.bin:/node_modules/.bin:/usr/local/bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/tmp/pipcook/node_modules/.bin:/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle @pipcook/plugins-textline-data-access@0.6.0~compile: CWD: /root/tmp/pipcook/packages/plugins/data-access/textline-data-access
10 silly lifecycle @pipcook/plugins-textline-data-access@0.6.0~compile: Args: [ '-c', 'tsc -b tsconfig.json' ]
11 silly lifecycle @pipcook/plugins-textline-data-access@0.6.0~compile: Returned: code: 1  signal: null
12 info lifecycle @pipcook/plugins-textline-data-access@0.6.0~compile: Failed to exec compile script
13 verbose stack Error: @pipcook/plugins-textline-data-access@0.6.0 compile: `tsc -b tsconfig.json`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid @pipcook/plugins-textline-data-access@0.6.0
15 verbose cwd /root/tmp/pipcook/packages/plugins/data-access/textline-data-access
```

environment：
ubuntu18.04(in docker container)
node: 12.14

**Comment by yorkie** [comment]
Closing because of inactivity.
