### ISSUE TITLE
cli: failed to run `pipcook daemon start` on my macOS

### ISSUE THREAD

**Issue by ivc369** [alibaba/pipcook#314]
### Operating system and NodeJS version(s):
* MacOS Catalina `10.15.5`
* NodeJS `v12.18.2`

### Pipcook version(s):
`v1.0.1`

I ran `pipcook daemon start` on MacOS and encountered the following error: 

![image](https://user-images.githubusercontent.com/16490377/86733300-aaea5280-c063-11ea-8a7c-9b13fb104c04.png)

**Comment by yorkie** [comment]
@ivc369 Thanks for your feedback, I have investigated this problem a bit, it might be caused by a failed `pipcook init`, then the daemon directory doesn't get created. However the Node.js child process's `fork()` will throw the ENOENT by calling the [`chdir(2)`](https://github.com/libuv/libuv/blob/v1.x/src/unix/process.c#L341-L344) with non-existed `cwd` path.

I think we could check the daemon related paths are set up correctly and give a better tip before executing the `pipcook-daemon(1)` commands.

/cc @FeelyChau

**Comment by FeelyChau** [comment]
@ivc369 it looks like the daemon is not installed successfully.
Could you re-run `pipcook init`, then try again?

**Comment by ivc369** [comment]
@FeelyChau I tried to run `sudo pipcook init` again, and then an exception occurred:

```bash
exec ""npm" install @pipcook/daemon -E --production"
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> @pipcook/boa@1.0.1 preinstall /Users/xxx/.pipcook/server/node_modules/@pipcook/boa
> node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js

/bin/rm
/usr/bin/make
/usr/bin/tar
/usr/bin/curl
make: Nothing to be done for `all'.
internal/fs/utils.js:230
    throw err;
    ^

Error: EACCES: permission denied, open '/Users/xxx/.pipcook/server/node_modules/@pipcook/boa/.CONDA_INSTALL_DIR'
    at Object.openSync (fs.js:458:3)
    at Object.writeFileSync (fs.js:1355:35)
    at exports.initAndGetCondaPath (/Users/xxx/.pipcook/server/node_modules/@pipcook/boa/tools/utils.js:31:6)
    at Object.<anonymous> (/Users/xxx/.pipcook/server/node_modules/@pipcook/boa/tools/install-python.js:15:26)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/Users/xxx/.pipcook/server/node_modules/@pipcook/boa/.CONDA_INSTALL_DIR'
}
npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pipcook/boa@1.0.1 preinstall: `node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @pipcook/boa@1.0.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2020-07-07T09_29_19_371Z-debug.log


...


+ @pipcook/pipboard@1.0.1
added 220 packages from 1178 contributors and audited 220 packages in 18.06s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

✖ failed to initialize Pipcook with the error Error: Command failed: "npm" install @pipcook/daemon -E --production
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at /usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:45:29
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:4:12)
    at npmInstall (/usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:29:12)
    at /usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:112:13
    at Generator.next (<anonymous>)
```

**Comment by FeelyChau** [comment]
Why use `sudo`? `pipcook init` will call `npm install` to install the packages, but it's not safe with `sudo`, look at:
https://docs.npmjs.com/misc/config#unsafe-perm
we have not support `--unsafe-perm` for now.

**Comment by yorkie** [comment]
@ivc369 Pipcook shouldn't need any extra permission to be working, may I ask you to try to init again without `sudo`?

**Comment by ivc369** [comment]
@FeelyChau @yorkie Oops.. It works without `sudo`! Thanks ;-)
