### ISSUE TITLE
pipcook init 报错

### ISSUE THREAD

**Issue by hi-liuyj** [alibaba/pipcook#403]
pipcook版本： 1.0.5
node版本：12.18.0
操作系统：macos 10.15.5
执行命令：`pipcook init --tuna`
报错1：
![image](https://user-images.githubusercontent.com/64191635/89262682-82ee0f00-d662-11ea-9b11-16f0f04ec716.png)
报错2：
![image](https://user-images.githubusercontent.com/64191635/89262714-95684880-d662-11ea-99b6-a11407c77b5b.png)
期望：不报错

**Comment by FeelyChau** [comment]
能确认下当前的 npm 源吗？
``` shell
$ npm config get registry
```
如果是 npm 的源的话应该是没问题的。

**Comment by hi-liuyj** [comment]
确认了上面的错误是用的公司源，midway有冲突。
换了npm源，速度实在太慢，又换成了淘宝源。

淘宝源下重装了`pipcook`，使用`pipcook init  --tuna`
报错：
```bash
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
make: *** ["/Users/liuyj/.pipcook/server/node_modules/@pipcook/boa/pybind11/src"] Error 56
npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @pipcook/boa@1.0.5 preinstall: `node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @pipcook/boa@1.0.5 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liuyj/.npm/_logs/2020-08-04T10_48_42_300Z-debug.log
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @icedesign/theme@1.2.1 requires a peer of moment@^2.22.1 but none is installed. You must install peer dependencies yourself.
npm WARN @icedesign/theme@1.2.1 requires a peer of @alifd/next@~1.19.19 but none is installed. You must install peer dependencies yourself.
npm WARN @alifd/next@1.19.31 requires a peer of moment@^2.22.1 but none is installed. You must install peer dependencies yourself.
npm WARN @alifd/next@1.20.24 requires a peer of moment@^2.22.1 but none is installed. You must install peer dependencies yourself.
npm WARN pipboard@1.0.0 No description
npm WARN pipboard@1.0.0 No repository field.

[fail]: failed to initialize Pipcook with the error Error: Command failed: "npm" install @pipcook/daemon -E --production
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at /Users/liuyj/.nvm/versions/node/v12.18.0/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:45:29
    at Generator.next (<anonymous>)
    at /Users/liuyj/.nvm/versions/node/v12.18.0/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/liuyj/.nvm/versions/node/v12.18.0/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:4:12)
    at npmInstall (/Users/liuyj/.nvm/versions/node/v12.18.0/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:29:12)
    at /Users/liuyj/.nvm/versions/node/v12.18.0/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:109:13
    at Generator.next (<anonymous>)

# npm error log
13153 verbose stack Error: @pipcook/boa@1.0.5 preinstall: `node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js`
13153 verbose stack Exit status 2
13153 verbose stack     at EventEmitter.<anonymous> (/Users/liuyj/.nvm/versions/node/v12.18.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13153 verbose stack     at EventEmitter.emit (events.js:315:20)
13153 verbose stack     at ChildProcess.<anonymous> (/Users/liuyj/.nvm/versions/node/v12.18.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13153 verbose stack     at ChildProcess.emit (events.js:315:20)
13153 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13153 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
13154 verbose pkgid @pipcook/boa@1.0.5
13155 verbose cwd /Users/liuyj/.pipcook/server
13156 verbose Darwin 19.5.0
13157 verbose argv "/Users/liuyj/.nvm/versions/node/v12.18.0/bin/node" "/Users/liuyj/.nvm/versions/node/v12.18.0/bin/npm" "install" "@pipcook/daemon" "-E" "--production"
13158 verbose node v12.18.0
13159 verbose npm  v6.14.7
13160 error code ELIFECYCLE
13161 error errno 2
13162 error @pipcook/boa@1.0.5 preinstall: `node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js`
13162 error Exit status 2
13163 error Failed at the @pipcook/boa@1.0.5 preinstall script.
13163 error This is probably not a problem with npm. There is likely additional logging output above.
13164 verbose exit [ 2, true ]
```
帮忙看看，多谢

**Comment by FeelyChau** [comment]
应该是下载 pybind11 依赖没成功，可以试试访问:
https://github.com/pybind/pybind11/archive/v2.4.3.tar.gz
慢的话开个可能得进行网络加速。

**Comment by yorkie** [comment]
Closing because of inactivity.

**Comment by WISZC** [comment]
> 应该是下载 pybind11 依赖没成功，可以试试访问:
> https://github.com/pybind/pybind11/archive/v2.4.3.tar.gz
> 慢的话开个可能得进行网络加速。

并没有解决问题

**Comment by yorkie** [comment]
@WISZC 可以发一下详细日志吗？我们具体再看一下。
