### ISSUE TITLE
ci/cd: pipeline workflow is still failing

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#492]
The Pipeline workflow is still failed as the following error:

```
[warn]: occurs an error on model trainer TypeError: Cannot read property 'len' of undefined
[warn]:     at Object.<anonymous> (/home/runner/.pipcook/plugins/node_modules/@pipcook/plugins-image-classification-tensorflow-model-train/dist/index.js:43:49)
[warn]:     at Generator.next (<anonymous>)
[warn]:     at fulfilled (/home/runner/.pipcook/plugins/node_modules/@pipcook/plugins-image-classification-tensorflow-model-train/dist/index.js:4:58)
[warn]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[fail]: something wrong when run job: TypeError: Cannot read property 'len' of undefined
    at Object.<anonymous> (/home/runner/.pipcook/plugins/node_modules/@pipcook/plugins-image-classification-tensorflow-model-train/dist/index.js:43:49)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/.pipcook/plugins/node_modules/@pipcook/plugins-image-classification-tensorflow-model-train/dist/index.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by yorkie** [comment]
@rickycao-qy May I ask you to take a look at this? It seems crashed on the plugin @pipcook/plugins-image-classification-tensorflow-model-train :(

**Comment by FeelyChau** [comment]
The pipeline tests have been fixed.
