### ISSUE TITLE
pipeline, daemon: plugin api timeout and incorrect exit code

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#517]
See https://github.com/alibaba/pipcook/runs/1034454213?check_suite_focus=true and the following log:

```
(node:4905) UnhandledPromiseRejectionWarning: Error: listen timeout: http://127.0.0.1:6927/api/plugin/event/75rwsfhb
    at Timeout._onTimeout (/home/runner/work/pipcook/pipcook/packages/sdk/dist/request.js:112:20)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:4905) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). 
```

There are 2 daemon bugs in this case:

1. API timeout.
2. incorrect exit code though something went wrong.

**Comment by FeelyChau** [comment]
We redesigned it in version 2.0, the daemon is no longer needed.
