### ISSUE TITLE
Job error

### ISSUE THREAD

**Issue by FeelyChau** [alibaba/pipcook#530]
When I run `npx ts-node ./run_tests.ts` to  test the sdk and at the same time, start a client to run
`./packages/cli/dist/bin/pipcook run ./example/pipelines/text-bayes-classification.json --tuna`, something goes wrong.

```shell
$ npx ts-node ./run_tests.ts
    ✓ create job
    ✓ query job info
    ✗ list job infos
      - Expected 'p6hr9dwv' to be 'yrvku4qi'.
    ✓ clean
```
```shell
$ ./packages/cli/dist/bin/pipcook run ./example/pipelines/text-bayes-classification.json --tuna
✔ plugin @pipcook/plugins-csv-data-collect@1.1.0 has already been installed
✔ plugin @pipcook/plugins-csv-data-access@1.1.0 has already been installed
✔ plugin @pipcook/plugins-bayesian-model-define@1.1.0 has already been installed
✔ plugin @pipcook/plugins-bayesian-model-train@1.1.0 has already been installed
✔ plugin @pipcook/plugins-bayesian-model-evaluate@1.1.0 has already been installed
ℹ start to create pipeline
✔ pipeline is created: 9wxwhq9g, installing
✔ pipeline installed successfully, start to run job
✔ job is created: yrvku4qi, running
ℹ start loading plugin @pipcook/plugins-csv-data-collect
⚠ start loading plugin @pipcook/plugins-csv-data-collect
ℹ start loading plugin @pipcook/plugins-csv-data-access
⚠ start loading plugin @pipcook/plugins-csv-data-access
ℹ create a result "6rv28fns" for plugin "@pipcook/plugins-csv-data-access@1.1.0"
⚠ create a result "6rv28fns" for plugin "@pipcook/plugins-csv-data-access@1.1.0"
ℹ start loading plugin @pipcook/plugins-bayesian-model-define
⚠ start loading plugin @pipcook/plugins-bayesian-model-define
✖ something wrong when run job: no job found
```
```shell
$ node ./packages/daemon/bootstrap.js
set env BOA_CONDA_MIRROR=https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda
single process mode is still in experiment, please don't use it in production environment
Server is listening at http://localhost:6927, cost 3.52453932s
trained the model to /path/to/.pipcook/components/43m1g1c7/output
trained the model to /path/to/.pipcook/components/s3vl8ucw/output
trained the model to /path/to/.pipcook/components/p6hr9dwv/output
unhandled error from log: TypeError: FileNotFoundError: [Errno 2] No such file or directory

At:
  /path/to/work/pipcook/packages/boa/.miniconda/lib/python3.7/posixpath.py(383): abspath
  /path/to/work/pipcook/packages/boa/.miniconda/lib/python3.7/posixpath.py(396): realpath
  /path/to/work/pipcook/packages/boa/.miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py(2331): normalize_path
  /path/to/work/pipcook/packages/boa/.miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py(2349): _normalize_cached
  /path/to/work/pipcook/packages/boa/.miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py(2039): find_on_path

    at Object.import (/path/to/work/pipcook/packages/boa/lib/index.js:435:35)
    at Object.<anonymous> (/path/to/.pipcook/plugins/node_modules/@pipcook/plugins-bayesian-model-define/dist/script.js:19:25)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/path/to/.pipcook/plugins/node_modules/@pipcook/plugins-bayesian-model-define/dist/index.js:36:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
trained the model to /path/to/.pipcook/components/1iawb1qw/output
```

**Comment by FeelyChau** [comment]
The reason is:
the sdk test cases will remove all jobs at the end, if the pipcook cli is still running a job, there will be an error as above.
But I found another problem when check this bug: #531 .
