### ISSUE TITLE
不论是本地安装cli还是docker安装都会报错

### ISSUE THREAD

**Issue by nannan9507** [alibaba/pipcook#6]
根据示例，在目录文件执行 pipcook init 时
```
# pipcook init
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNREFUSED 151.101.228.133:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '151.101.228.133',
  port: 443
}

```

但是pip-project文件确实可以成功生成，

然后执行 node examples/pipeline-mnist-image-classfication.js时

```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@pipcook/pipcook-core'
Require stack:
- /document/pipcook-project/examples/pipeline-mnist-image-classfication.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/document/pipcook-project/examples/pipeline-mnist-image-classfication.js:23:86)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/document/pipcook-project/examples/pipeline-mnist-image-classfication.js'
  ]
}
```

**Comment by utkobe** [comment]
报错的 151.101.228.133 是 github 的 ip， 可能是本地网络请求 github 的资源有问题，这边把资源放在阿里云上了，麻烦更新一下 pipcook-cli, (本地重新 sudo npm install @pipcook/pipcook-cli -g)， 再试一下

**Comment by nannan9507** [comment]
3Q！这次能正常跑起来了，不过在安装下面插件之前，还是报错了这么一个错，不过不影响下面插件的安装，而且最后也能开始训练模型了

```
Error: download error
    at downloadConfig (/usr/local/lib/node_modules/@pipcook/pipcook-cli/lib/init.js:91:11)
    at init (/usr/local/lib/node_modules/@pipcook/pipcook-cli/lib/init.js:43:13)
    at Command.<anonymous> (/usr/local/lib/node_modules/@pipcook/pipcook-cli/bin/index.js:33:5)
    at Command.listener (/usr/local/lib/node_modules/@pipcook/pipcook-cli/node_modules/commander/index.js:360:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (/usr/local/lib/node_modules/@pipcook/pipcook-cli/node_modules/commander/index.js:799:12)
    at Command.parse (/usr/local/lib/node_modules/@pipcook/pipcook-cli/node_modules/commander/index.js:563:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/@pipcook/pipcook-cli/bin/index.js:77:9)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

**Comment by utkobe** [comment]
@nannan9507  这边会先 请求 github，如果失败再拿本地的 pipcook config资源，所以会打印一个 download error, 不影响使用，如果功能检查正常，麻烦 close 一下 issue，多谢，祝您新年快乐
（下载失败有可能是因为本地有代理或者 ssl 证书影响，您可以尝试一下 node 的 request 库，看一下能不能正常下载其他网络资源）

**Comment by peng** [comment]
@nannan9507  你的位置是在哪里？

**Comment by nannan9507** [comment]
@peng 不好意思现在才看到，我在杭州，阿里西溪园区附近的公司

顺便一问，后续会开放 比如 input 输入框，各种组件的数据集吗？比如我们用框架的人也可以添加数据集，和现有一套用于前端的数据集

**Comment by utkobe** [comment]
@nannan9507  我们后续会开源 imgcook 沉淀的组件识别的数据集，同时，我们在规划构建一套前端标准的大规模数据集

**Comment by nannan9507** [comment]
好的3q，很棒的项目 解放劳动力，之前自己去配过 YOLO 去做识别，卡在了数据集这一步，也没有什么途径和成本去搞这个，公司也没有算法工程师
