### ISSUE TITLE
job is failed: TypeError: the plugin(@pipcook/plugins-mnist-data-collect@1.1.0) not loaded.

### ISSUE THREAD

**Issue by mrzhangweichao** [alibaba/pipcook#692]
✔ plugin @pipcook/plugins-mnist-data-collect@1.1.0 has already been installed
✔ plugin @pipcook/plugins-pascalvoc-data-access@1.1.0 has already been installed
✔ plugin @pipcook/plugins-tensorflow-image-classification-process@1.1.4 has already been installed
✔ plugin @pipcook/plugins-tfjs-simplecnn-model-define@1.1.0 has already been installed
✔ plugin @pipcook/plugins-image-classification-tfjs-model-train@1.1.3 has already been installed
✔ plugin @pipcook/plugins-image-classification-tfjs-model-evaluate@1.1.1 has already been installed
ℹ start to create pipeline
✔ pipeline is created: zzc6ldkh, installing
ℹ plugin @pipcook/plugins-mnist-data-collect@1.1.0 already installed
ℹ plugin @pipcook/plugins-pascalvoc-data-access@1.1.0 already installed
ℹ plugin @pipcook/plugins-tensorflow-image-classification-process@1.1.4 already installed
ℹ plugin @pipcook/plugins-tfjs-simplecnn-model-define@1.1.0 already installed
ℹ plugin @pipcook/plugins-image-classification-tfjs-model-train@1.1.3 already installed
ℹ plugin @pipcook/plugins-image-classification-tfjs-model-evaluate@1.1.1 already installed
✔ pipeline installed successfully, start to run job
✔ job is created: p7lfcvds, running
ℹ [job] running
ℹ [job] running dataCollect start
ℹ start loading plugin @pipcook/plugins-mnist-data-collect
⚠ 2021-01-15 16:54:42.813965: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
⚠ 2021-01-15 16:54:42.876015: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x10b591dd0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
⚠ 2021-01-15 16:54:42.876066: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
ℹ [job] fails
✖ job is failed: TypeError: the plugin(@pipcook/plugins-mnist-data-collect@1.1.0) not loaded.
    at /Users/zhangweichao/.pipcook/server/node_modules/@pipcook/costa/dist/client/entry.js:133:23
    at Generator.next (<anonymous>)
    at /Users/zhangweichao/.pipcook/server/node_modules/@pipcook/costa/dist/client/entry.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/zhangweichao/.pipcook/server/node_modules/@pipcook/costa/dist/client/entry.js:4:12)
    at emitStart (/Users/zhangweichao/.pipcook/server/node_modules/@pipcook/costa/dist/client/entry.js:125:12)
    at /Users/zhangweichao/.pipcook/server/node_modules/@pipcook/costa/dist/client/entry.js:226:13
    at Generator.next (<anonymous>)
    at /Users/zhangweichao/.pipcook/server/node_modules/@pipcook/costa/dist/client/entry.js:8:71
    at new Promise (<anonymous>)

**Comment by FeelyChau** [comment]
Could you restart daemon with:
```sh
$ pipcook daemon debug
```
and run the pipeline again for more details?

**Comment by momo-kit** [comment]
相同的问题
![image](https://user-images.githubusercontent.com/44059402/105028493-0faf4c80-5a8c-11eb-8638-9c12a1b8227c.png)

**Comment by AngusYang9** [comment]
I have the same problem, how to solve this error?

**Comment by FeelyChau** [comment]
> 相同的问题
> ![image](https://user-images.githubusercontent.com/44059402/105028493-0faf4c80-5a8c-11eb-8638-9c12a1b8227c.png)

日志看起来是没有正确安装 python 依赖，可能需要重新安装一下 `@pipcook/plugins-tensorflow-image-classification-process`.

The log errors show the dependencies of python module is not installed, try to reinstall the plugin  `@pipcook/plugins-tensorflow-image-classification-process`.

**Comment by FeelyChau** [comment]
> I have the same problem, how to solve this error?

Could you post the log? Or you can try to  reinstall the plugin first.
