### ISSUE TITLE
pipcook init error in ubuntu 18.04

### ISSUE THREAD

**Issue by shouhou-web** [alibaba/pipcook#710]
根据以前issue，安装过Ubuntu-make，确认过npm源为淘宝源，但依然不成功

报错信息如下：
Error: Command failed: curl https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh > Miniconda3-4.7.12.1-Linux-x86_64.sh
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at exports.run (/home/shouhou/.pipcook/server/node_modules/@pipcook/boa/tools/utils.js:20:19)
    at Object.<anonymous> (/home/shouhou/.pipcook/server/node_modules/@pipcook/boa/tools/install-python.js:37:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 3526,
  stdout: null,
  stderr: null
}
npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pipcook/boa@1.3.0 preinstall: `node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pipcook/boa@1.3.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shouhou/.npm/_logs/2021-01-31T05_29_22_862Z-debug.log
✖ failed to initialize Pipcook with the error Error: Command failed: "npm" install @pipcook/daemon -E --production
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at /usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:27:25
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:4:12)
    at npmInstall (/usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:24:12)
    at /usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:152:15
    at Generator.next (<anonymous>)

**Comment by yorkie** [comment]
可以试试 `pipcook init --tuna -c cnpm`.

**Comment by FeelyChau** [comment]
Pipcook 2.0 已发布，解决了安装过程中的各种问题，你可以通过以下命令卸载 v1.0 和安装 v2:
```sh
$ npm uninstall @pipcook/pipcook-cli -g && npm install @pipcook/cli -g
```

**Comment by FeelyChau** [comment]
这个 issue 先关闭了，有任何问题可以重新打开新的 issue。
