### ISSUE TITLE
实例文档是否错误？

### ISSUE THREAD

**Issue by ShanaMaid** [alibaba/pipcook#753]
![image](https://user-images.githubusercontent.com/20333903/113986059-66544780-987f-11eb-8507-be97c72fa895.png)

下载的passcalvoc数据集，为什么用coco进行分析呢？

**Comment by rickycao-qy** [comment]
第二层是数据接入层，类似于数据集合模型之间的桥梁，如果下载的是 pascal 的数据集，但是模型需要的是 coco 格式，那么需要 coco-data-access 进行转化

**Comment by ShanaMaid** [comment]
执行结果和文档描述不一致呢
```
const predict = require('./output');
(async () => {
  const v1 = await predict('./zz.png');
  console.log(v1); 
  
})();
```

Overriding model.yaml nc=80 with nc=2

[None]

![image](https://user-images.githubusercontent.com/20333903/113988656-42decc00-9882-11eb-877b-2ee76a774596.png)

**Comment by rickycao-qy** [comment]
是完全执行的原始的教程的步骤吗，图片也是一样的吗

**Comment by ShanaMaid** [comment]
用label-image自己标注的图片，为了快速测试，只配置了一张。

**Comment by rickycao-qy** [comment]
应该是因为当前图片没有检测出目标，所以会返回 None

**Comment by ShanaMaid** [comment]
识别图片和训练图片用的都是同一张

**Comment by ShanaMaid** [comment]
并且直接require('./output')会报错
```
import sys
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

```

参照https://github.com/alibaba/pipcook/issues/690#issuecomment-759451928修改了_requirePlugin才能执行。

执行结果就是
```
Overriding model.yaml nc=80 with nc=2

[None]

```

**Comment by rickycao-qy** [comment]
是不是预测逻辑有点问题，模型定义插件的源码在  https://github.com/imgcook/pipcook-plugin-pytorch-yolov5-model/blob/main/__init__.py 我们尽快检查一下，同时有兴趣也可以贡献一下哦，python 插件预测的时候加载报错的问题会同步支持一下

**Comment by yorkie** [comment]
@rickycao-qy @FeelyChau 我们是不是可以在 2.0 版本中支持目标检测？

**Comment by FeelyChau** [comment]
> @rickycao-qy @FeelyChau 我们是不是可以在 2.0 版本中支持目标检测？

正在考虑如何迁移 YOLO v5.

**Comment by FeelyChau** [comment]
@ShanaMaid Pipcook 2.0 已支持目标检测，参考文档: https://alibaba.github.io/pipcook/#/zh-cn/
