### ISSUE TITLE
pipcook init失败（mac M1芯片）

### ISSUE THREAD

**Issue by Daniel6Lee** [alibaba/pipcook#799]
系统：macOS 11.2.3 M1芯片
node版本：v16.2.0
npm版本：6.14.13
切换到淘宝源和原始的源都是同样的错误，一直没能找到解决方案，麻烦帮忙看看：
Error: Command failed: sh ./Miniconda3-4.7.12.1-MacOSX.sh -f -b -p /Users/daniel/.pipcook/server/node_modules/@pipcook/boa/.miniconda
    at checkExecSyncError (node:child_process:707:11)
    at execSync (node:child_process:744:15)
    at exports.run (/Users/daniel/.pipcook/server/node_modules/@pipcook/boa/tools/utils.js:20:19)
    at Object.<anonymous> (/Users/daniel/.pipcook/server/node_modules/@pipcook/boa/tools/install-python.js:43:3)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 81433,
  stdout: null,
  stderr: null
}
npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pipcook/boa@1.3.1 preinstall: `node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pipcook/boa@1.3.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daniel/.npm/_logs/2021-06-28T13_01_17_374Z-debug.log
✖ failed to initialize Pipcook with the error Error: Command failed: "npm" install @pipcook/daemon -E --production
    at checkExecSyncError (node:child_process:707:11)
    at Object.execSync (node:child_process:744:15)
    at /opt/homebrew/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:27:25
    at Generator.next (<anonymous>)
    at /opt/homebrew/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/homebrew/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:4:12)
    at npmInstall (/opt/homebrew/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:24:12)
    at /opt/homebrew/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:152:15
    at Generator.next (<anonymous>)

**Comment by FeelyChau** [comment]
M1 芯片的支持还有一些问题，我们将在 2.x 的某个版本修复它，你有兴趣的话也可以修复一下 :)

**Comment by Daniel6Lee** [comment]
嗯嗯好，谢谢！

**Comment by ckdlbc** [comment]
请问对M1的支持有任何进展吗？ @FeelyChau

**Comment by liting-yes** [comment]
已经23年了，2.x版本还没发，我下载也报错😂
