### ISSUE TITLE
安装pipcook失败

### ISSUE THREAD

**Issue by tiancaidiyibu** [alibaba/pipcook#818]
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /opt/homebrew/lib/node_modules/@pipcook/cli
npm ERR! dest /opt/homebrew/lib/node_modules/@pipcook/.cli-Ka4e2zSq
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/opt/homebrew/lib/node_modules/@pipcook/cli' -> '/opt/homebrew/lib/node_modules/@pipcook/.cli-Ka4e2zSq'
npm ERR!  [Error: EACCES: permission denied, rename '/opt/homebrew/lib/node_modules/@pipcook/cli' -> '/opt/homebrew/lib/node_modules/@pipcook/.cli-Ka4e2zSq'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/opt/homebrew/lib/node_modules/@pipcook/cli',
npm ERR!   dest: '/opt/homebrew/lib/node_modules/@pipcook/.cli-Ka4e2zSq'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2021-08-02T01_37_20_304Z-debug.log

**Comment by tiancaidiyibu** [comment]
> 操作系统：11.4（M1芯片）
> node版本：v16.4.> at Object. (/opt/homebrew/lib/node_modules/@pipcook/cli/node_modules/_@pipcook_boa@2.1.0@@pipcook/boa/tools/install-python.js:31:3)
> at Module._compile (node:internal/modules/cjs/loader:1095:14)
> at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
> at Module.load (node:internal/modules/cjs/loader:975:32)
> at Function.Module._load (node:internal/modules/cjs/loader:816:12)
> at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
> at node:internal/main/run_main_module:17:47 {
> status: 2,
> signal: null,
> output: [ null, null, null ],
> pid: 73220,
> stdout: null,
> stderr: null
> }
> [npminstall:runscript:error] @pipcook/boa@^2.1.0 scripts.install run "node-pre-gyp install --fallback-to-build=false || npm run build" error: Error [RunScriptError]: Run "sh -c node-pre-gyp install --fallback-to-build=false || npm run build" error, exit code 1
> at ChildProcess. (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
> at ChildProcess.emit (node:events:394:28)
> at maybeClose (node:internal/child_process:1067:16)
> at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
> stdio: [Object],
> exitcode: 1
> }
> Install fail! RunScriptError: post install error, please remove node_modules before retry!
> Run "sh -c node-pre-gyp install --fallback-to-build=false || npm run build" error, exit code 1
> RunScriptError: Run "sh -c node-pre-gyp install --fallback-to-build=false || npm run build" error, exit code 1
> at ChildProcess. (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
> at ChildProcess.emit (node:events:394:28)
> at maybeClose (node:internal/child_process:1067:16)
> at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
> npminstall version: 3.28.0
> npminstall args: /opt/homebrew/Cellar/node/16.4.0/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/Users/mac/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.nlark.com -g @pipcook/cli

**Comment by tiancaidiyibu** [comment]
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /opt/homebrew/lib/node_modules/@pipcook/cli/node_modules/@pipcook/boa
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.4.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.8.2 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! (node:78692) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/@pipcook/cli/node_modules/@pipcook/boa/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mac/Library/Caches/node-gyp/16.4.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/mac/Library/Caches/node-gyp/16.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/mac/Library/Caches/node-gyp/16.4.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/opt/homebrew/lib/node_modules/@pipcook/cli/node_modules/@pipcook/boa',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.5.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/16.4.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /opt/homebrew/lib/node_modules/@pipcook/cli/node_modules/@pipcook/boa
npm ERR! gyp ERR! node -v v16.4.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2021-08-02T02_21_02_983Z-debug.log

**Comment by yorkie** [comment]
看起来是 m1 macbook，目前 boa 的预构建（node-pre-gyp）还没有支持。

**Comment by tiancaidiyibu** [comment]
@yorkie 目前是无解的吗？

**Comment by FeelyChau** [comment]
> @yorkie 目前是无解的吗？

有计划把 boa 做成可选安装，这样 m1 就可以安装和运行非 python 链路的 pipeline 了。

**Comment by ilyp** [comment]
@yorkie 不只是M1，我mac版本11.5，非M1CPU，使用npm也会报这个错误，一个月前安装还没问题。目前使用cnpm安装成功了

**Comment by tiancaidiyibu** [comment]
@ilyp 请问用的是什么源呢

**Comment by ilyp** [comment]
> @ilyp 请问用的是什么源呢

淘宝镜像 https://registry.npm.taobao.org

**Comment by FeelyChau** [comment]
> @yorkie 不只是M1，我mac版本11.5，非M1CPU，使用npm也会报这个错误，一个月前安装还没问题。目前使用cnpm安装成功了

可以试试现在的 pipcook v2.1.4版本，安装速度和易用性方面有非常大的提升。
