### ISSUE TITLE
boa init error

### ISSUE THREAD

**Issue by PanYuntao** [alibaba/pipcook#953]
# node -v
v17.3.0
# npm -v
8.3.0
Centos8

cnpm install @pipcook/boa
⠴ [0/1] Installing ms@2.1.2
[npminstall:runscript] @pipcook/boa@latest found binding.gyp file, auto run "node-gyp rebuild", root: "/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa"
> @pipcook/boa@latest preinstall /root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa
⠦ [0/1] Installing ms@2.1.2
sh "command -v rm"
/bin/rm
sh "command -v make"
/usr/bin/make
sh "command -v tar"
/bin/tar
sh "command -v wget"
/usr/bin/wget
make: Entering directory '/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/pybind11'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
⠋ [0/1] Installing ms@2.1.2
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
rm -rf "/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/pybind11/src"
mkdir -p "/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/pybind11/downloads"
[ -f "/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/pybind11/downloads/pybind11-v2.4.3.tgz" ] || wget -O "/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/pybind11/downloads/pybind11-v2.4.3.tgz" https://github.com/pybind/pybind11/archive/v2.4.3.tar.gz
⠙ [0/1] Installing ms@2.1.2
⠹ [0/1] Installing ms@2.1.2
⠏ [0/1] Installing ms@2.1.2
302 Found
Location: https://codeload.github.com/pybind/pybind11/tar.gz/refs/tags/v2.4.3 [following]
--2023-02-22 09:42:55--  https://codeload.github.com/pybind/pybind11/tar.gz/refs/tags/v2.4.3
⠋ [0/1] Installing ms@2.1.2
⠧ [0/1] Installing ms@2.1.2
200 OK
Length: unspecified [application/x-gzip]
Saving to: '/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/pybind11/downloads/pybind11-v2.4.3.tgz'
⠹ [0/1] Installing ms@2.1.2
/root/python_test/node_modules/.store/@p     [  <=>                                                                              ] 557.74K  1.40MB/s    in 0.4s

2023-02-22 09:42:56 (1.40 MB/s) - '/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/pybind11/downloads/pybind11-v2.4.3.tgz' saved [571127]

md5sum --quiet --check checksums
tar -C "/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/pybind11/downloads" -xf "/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/pybind11/downloa⠸ [0/1] Installing ms@2.1.2
mv "/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/pybind11/downloads/pybind11-2.4.3" "/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/pybind11/src"
# apply patches
patch -u -b src/include/pybind11/pytypes.h -i patches/2.4.3-fix-object-destruct.patch
patching file src/include/pybind11/pytypes.h
make: Leaving directory '/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/pybind11'
sh "curl https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh > Miniconda3-4.7.12.1-Linux-x86_64.sh"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
⠏ [0/1] Installing ms@2.1.2
 46 68.4M   46 32.0M    0     0   477k      0  0:02:26  0:01:08  0:01:18     0
curl: (18) transfer closed with 38230568 bytes remaining to read
node:child_process:903
    throw err;
    ^

Error: Command failed: curl https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh > Miniconda3-4.7.12.1-Linux-x86_64.sh
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at exports.run (/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/tools/utils.js:20:19)
    at Object.<anonymous> (/root/python_test/node_modules/.store/@pipcook+boa@1.3.1/node_modules/@pipcook/boa/tools/install-python.js:37:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  status: 18,
  signal: null,
  output: [ null, null, null ],
  pid: 3656,
  stdout: null,
  stderr: null
}

Node.js v17.3.0
[npminstall:runscript:error] @pipcook/boa@latest run preinstall node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js error: Error: Command failed with exit code 1: node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js
    at makeError (/usr/local/lib/node_modules/cnpm/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/local/lib/node_modules/cnpm/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.exports.runScript (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/utils.js:262:12)
    at async runLifecycleScripts (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/lifecycle_scripts.js:64:7)
    at async _install (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/install_package.js:318:5)
    at async install (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/install_package.js:23:12)
    at async _installOne (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/local_install.js:214:15)
    at async mapper (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/local_install.js:139:5) {
  shortMessage: 'Command failed with exit code 1: node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js',
  command: 'node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js',
  escapedCommand: 'node "tools/check-dependence.js" "&&" make -C "./pybind11/" "&&" node "tools/install-python.js" "&&" node "tools/install-requirements.js"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

**Comment by FeelyChau** [comment]
some issue #954
